on:
  pull_request:
    types: [closed]

jobs:
  bump_version:
    runs-on: ubuntu-20.04

    steps:
      - name: Dump GitHub context for merge
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}

      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9

      - name: save label
        id: savey
        run: echo "label=${{steps.pr-labels.outputs.labels}}" >> $GITHUB_OUTPUT

      - name: print output
        run: echo ${{steps.savey.outputs.label}}

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          skip-tag: "true"
          target-branch: "master"
          version-type: "major"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clean_up:
    needs: bump_version
    runs-on: ubuntu-latest

    steps:
      - name: delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
