on:
  pull_request:

jobs:
  dump_github:
    runs-on: ubuntu-20.04

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9

      - name: save label
        id: savey
        run: echo "label=${{steps.pr-labels.outputs.labels}}" >> $GITHUB_OUTPUT

      - name: print output
        run: echo ${{steps.savey.outputs.label}}

      - name: Check if output is empty
        run: |
          if [ -z "${{ steps.savey.outputs.label }}" ]; then
            echo "Output is empty"
            # You can add additional commands here to handle the empty output scenario
          else
            echo "Output is not empty"
          fi

      - name: trim output
        if: ${{steps.savey.outputs.label}} ==
        id: trimLabel
        run: |
          TRIM=$(echo "${{steps.savey.outputs.label}}" | sed 's/ //g')
          echo "trimmedLabel=$TRIM" >> $GITHUB_OUTPUT

      - name: print output
        run: echo ${{steps.trimLabel.outputs.trimmedLabel}}
