on:
  pull_request:

jobs:
  dump_github:
    runs-on: ubuntu-20.04

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9

      - name: save label
        id: savey
        run: echo "label=${{steps.pr-labels.outputs.labels}}" >> $GITHUB_OUTPUT

      - name: print output
        run: echo ${{steps.savey.outputs.label}}

      - name: trim output
        if: steps.savey.outputs.label != ''
        id: trimLabel
        run: |
          TRIM=$(echo "${{steps.savey.outputs.label}}" | sed 's/ //g')
          echo "trimmedLabel=$TRIM" >> $GITHUB_OUTPUT
