on:
  pull_request:

jobs:
  dump_github:
    runs-on: ubuntu-20.04

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.9

      - name: print label
        run: echo ${{steps.pr-labels.outputs}}
